// Measure character widths via SVG <text> + getBBox (matches Mermaid's
// htmlLabels:false text rendering path). Outputs Rust code for the
// CHAR_WIDTHS table in src/text_browser_metrics.rs.
//
// Uses system Arial font (via font-family="Arial, sans-serif").
//
// Usage: node measure_chars_svg.mjs > /tmp/widths.rs

import puppeteer from 'puppeteer';

const SIZES = [10, 12, 14, 16, 17, 18, 20, 24];
const CHARS = [];
// ASCII printable except space (measured separately as 0)
for (let c = 0x20; c <= 0x7E; c++) CHARS.push(String.fromCharCode(c));
// Common Unicode used in Mermaid diagrams
CHARS.push('«', '»', '–', '—', '…');

const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.setContent(`<!DOCTYPE html>
<html><body style="margin:0;padding:0;background:#fff;">
  <svg id="svg" xmlns="http://www.w3.org/2000/svg" width="500" height="500"
       style="position:absolute;visibility:hidden;">
    <text id="t" x="0" y="100" font-family="Arial, sans-serif"></text>
  </svg>
</body></html>`);

const widths = {};   // {size: {char: width}}

for (const size of SIZES) {
  widths[size] = {};
  for (const ch of CHARS) {
    const w = await page.evaluate(({ ch, size }) => {
      const t = document.getElementById('t');
      t.setAttribute('font-size', `${size}px`);
      // Measure advance width using "MxxxxxxxxxxM" trick: difference between
      // 10x and 0x repeats gives the actual per-glyph advance (incl. bearings),
      // which is what Mermaid sums when computing string widths.
      // For chars like space that have no bbox, fall back to direct repeat.
      const n = 10;
      t.textContent = ch.repeat(n);
      const w10 = t.getBBox().width;
      t.textContent = ch.repeat(n + 1);
      const w11 = t.getBBox().width;
      return w11 - w10;
    }, { ch, size });
    widths[size][ch] = w;
  }
}

await browser.close();

// Emit Rust code in the same format as text_browser_metrics.rs
let out = '';
out += '// Auto-generated by visual-regression/measure_chars_svg.mjs — DO NOT EDIT MANUALLY.\n';
out += '// Browser-measured Arial character widths via SVG <text> getBBox (htmlLabels:false path).\n\n';
out += 'use std::collections::HashMap;\n\n';
out += 'pub fn browser_char_width(c: char, font_size: f64) -> Option<f64> {\n';
out += `    const SIZES: &[u32] = &[${SIZES.join(', ')}];\n`;
out += `    let lower = SIZES.iter().filter(|&&s| s as f64 <= font_size).copied().last();
    let upper = SIZES.iter().filter(|&&s| s as f64 >= font_size).copied().next();
    match (lower, upper) {
        (Some(lo), Some(hi)) if lo == hi => CHAR_WIDTHS.get(&lo)?.get(&c).copied(),
        (Some(lo), Some(hi)) => {
            let w_lo = CHAR_WIDTHS.get(&lo)?.get(&c).copied()?;
            let w_hi = CHAR_WIDTHS.get(&hi)?.get(&c).copied()?;
            let t = (font_size - lo as f64) / (hi as f64 - lo as f64);
            Some(w_lo + t * (w_hi - w_lo))
        }
        (Some(lo), None) => CHAR_WIDTHS.get(&lo)?.get(&c).copied(),
        (None, Some(hi)) => CHAR_WIDTHS.get(&hi)?.get(&c).copied(),
        (None, None) => None,
    }
}\n\n`;

out += 'pub fn measure_browser(text: &str, font_size: f64) -> (f64, f64) {\n';
out += '    let width: f64 = text.chars().map(|c| browser_char_width(c, font_size).unwrap_or(font_size * 0.5)).sum();\n';
out += '    let height = font_size * 1.162;\n';
out += '    (width, height)\n';
out += '}\n\n';

out += '/// Same as `measure_browser`, returned separately for code that wants exact pixel widths.\n';
out += 'pub fn measure_exact(text: &str, font_size: f64) -> (f64, f64) { measure_browser(text, font_size) }\n\n';

out += 'pub static CHAR_WIDTHS: std::sync::LazyLock<HashMap<u32, HashMap<char, f64>>> =\n';
out += '    std::sync::LazyLock::new(|| {\n';
out += '        let mut sizes = HashMap::new();\n';
for (const size of SIZES) {
  out += '        {\n';
  out += '            let mut m = HashMap::new();\n';
  for (const ch of CHARS) {
    const cp = ch.codePointAt(0).toString(16).padStart(4, '0');
    out += `            m.insert('\\u{${cp}}', ${widths[size][ch].toFixed(8)}_f64);\n`;
  }
  out += `            sizes.insert(${size}_u32, m);\n`;
  out += '        }\n';
}
out += '        sizes\n';
out += '    });\n';

process.stdout.write(out);
